name: Question
description: Ask a question about the Zumic Python client
title: "[QUESTION] <short summary>"
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        👋 **Welcome!**

        This issue tracker is primarily for reporting bugs and suggesting improvements to the **Zumic Python client**.

        For general usage questions, please check our community resources first:
        - [Zumic Community Chat (Pachca)](https://app.pachca.com/join?invite_token=EakW3nIgma_ezqFc&company_name=Zumic+Community&company_id=416542)
        - [Zumic Discussions](https://github.com/zumicTeam/discussions)

        Please also search existing issues before submitting your question.

        ---
        If you still have a question about using or extending the Python client, please describe it below:

  - type: textarea
    id: your_question
    attributes:
      label: Your question
      description: Please clearly describe your question about the Python client.
      placeholder: |
        Example:
        How can I configure the client to work with a custom socket timeout?
    validations:
      required: true
